# Basic Site Settings
locale          : "en-US"
site_theme      : "air" # Options: "default", "air", "sunrise", "mint", "dirt", "contrast"
title           : "Kaila Christini, MsPH, MS | Cancer Prevention Researcher"
title_separator : "-"
name            : &name "Kaila Christini, MsPH, MS"
description     : &description "Cancer prevention researcher focused on population health, rural disparities, and health systems interventions."
url             : "https://kailachristini.github.io"
baseurl         : ""
repository      : "kailachristini/kailachristini.github.io"

# Homepage teaser / hero image
teaser          : "HCI_flowers.jpg" # image should be in /images/

# Site Author / Profile
author:
  avatar         : "KailaPhoto_Headshot.png" # will display as a nice circular image
  name           : "Kaila Christini, MsPH, MS"
  pronouns       : "She/Her/Hers ([Why pronouns matter](https://pronouns.org/what-and-why))"
  bio            : "Cancer prevention researcher, program manager, and PhD student at the University of Utah. Focused on population health, rural disparities, and health systems interventions."
  location       : "Earth"
  employer       : "Huntsman Cancer Institute | University of Utah"
  uri            : "https://www.hci.utah.edu/huntsman/labs/kepka"
  email          : "kaila.christini@hci.utah.edu"

  # Academic / social links
  academia       : "https://kailachristini.github.io/academicpages.github.io/"
  googlescholar  : "https://scholar.google.com/scholar?q=kaila+christini+OR+kaila+mcdonald"
  orcid          : "https://orcid.org/0000-0002-1157-3934"
  pubmed         : "https://www.ncbi.nlm.nih.gov/pubmed/?term=kaila+christini+OR+kaila+mcdonald"
  linkedin       : "https://www.linkedin.com/in/kaila-mcdonald-christini"

# Publication categories
publication_category:
  books        : { title: 'Books' }
  manuscripts  : { title: 'Journal Articles' }
  conferences  : { title: 'Conference Papers' }

# Site Settings
breadcrumbs        : false
words_per_minute   : 160
future             : true
read_more          : "disabled"
talkmap_link       : false
